### ISSUE TITLE
Acceso directo al SQL

### ISSUE THREAD

**Issue by enlues** [penicolas/NppFwbatch#4]
El acceso directo al SQL o mensajes debería ser con CTRL+Click en el texto, no por acceso directo de 4 teclas

**Comment by juanjo78git** [comment]
Puede que esto sirva de algo: https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

**Comment by juanjo78git** [comment]
Siempre se puede intentar añadir las opciones al menú contextual: http://docs.notepad-plus-plus.org/index.php/Context_Menu

**Comment by penicolas** [comment]
@juanjo78git a mi esta solución me gusta. El `clic-and-go` es una [utopía](http://www.channel4.com/programmes/utopia).

**Comment by enlues** [comment]
Acepto el menu contextual como útil, no me vale una combinación de 18 teclas...

**Comment by penicolas** [comment]
Entonces doy por cerrada la incidencia, ya que se abordará por medio de `Context_Menu` que nos indicaba @juanjo78git.
