### ISSUE TITLE
La función "Search in SQL" debería buscar por sql.CADENA

### ISSUE THREAD

**Issue by penicolas** [penicolas/NppFwbatch#6]
En la actualidad la función "***Search in SQL***" recupera la palabra bajo el cursor y la busca directamente en el fichero `sql`. Esto puede provocar problemas si la palabra aparece en alguna de las consultas.

Sería mejor que la búsqueda se realizara por algo como `sql.PALABRA.*.cmd` que es el nombre que recibe la referencia del `sql` en el propertie.

En el [plugin para `vim`](https://github.com/penicolas/fwblittle.vim) se realiza [algo similar](https://github.com/penicolas/fwblittle.vim/blob/master/plugin/fwblittle.vim#L438). Atención al SPAM que acabo de hacer.

**Comment by juanjo78git** [comment]
Además de solucionar este problema ahora la búsqueda de los mensajes lo hace por toda la cadena sobre la que está el cursos, es decir, cuenta los puntos como caracter de una palabra.

**Comment by penicolas** [comment]
Juanjo está en modo: `Veni, vidi, vici`.
